import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PWA",
  description: "Generated by create next app",
  manifest:'/manifest.json',
  generator:'Next.js',
  keywords:['next.js','next14','pwa','next-pwa'],
  themeColor:[{media:"(prefers-color-scheme:dark)",color:"#fff"}]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="default" />
  <meta name="apple-mobile-web-app-title" content="Your App Name" />
  <link rel="apple-touch-icon" href="/icon-192x192.png" />
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
